### PR TITLE
Compatibility fixes for building on Windows.

### LINKED ISSUE #482: rocBLAS configure failing to find OPENBLAS on Windows with -DBUILD_TESTING=ON
Configure and build for the `rocBLAS` CMake target succeeds with `-DBUILD_TESTING=OFF`. Fails with `-DBUILD_TESTING=ON`.

Logs:

```
[build] [12/16  75% :: 11.491] Configure sub-project rocBLAS (in background)
[build] FAILED: math-libs/BLAS/rocBLAS/stamp/configure.stamp math-libs/BLAS/rocBLAS/build/CMakeCache.txt math-libs/BLAS/rocBLAS/build/cmake_install.cmake compile_commands_fragment_rocBLAS.json D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/stamp/configure.stamp D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/build/CMakeCache.txt D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/build/cmake_install.cmake D:/projects/TheRock/build/compile_commands_fragment_rocBLAS.json 
[build] C:\Windows\system32\cmd.exe /C "cd /D D:\projects\TheRock\build\math-libs\BLAS\rocBLAS\build && d:\projects\TheRock\.venv\Scripts\python D:/projects/TheRock/build_tools/teatime.py --log-timestamps --label "rocBLAS configure" --interactive D:/projects/TheRock/build/logs/rocBLAS_configure.log -- "C:/Program Files/CMake/bin/cmake.exe" -GNinja -BD:/projects/TheRock/build/math-libs/BLAS/rocBLAS/build -SD:/projects/TheRock/math-libs/BLAS/rocBLAS -DCMAKE_INSTALL_PREFIX=D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/stage -DTHEROCK_STAGE_INSTALL_ROOT=D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/stage -DCMAKE_TOOLCHAIN_FILE=D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/_toolchain.cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/_init.cmake -DHIP_PLATFORM=amd -DROCM_PATH= -DROCM_DIR= -DBUILD_WITH_TENSILE=OFF -DBUILD_WITH_HIPBLASLT=OFF -DTensile_TEST_LOCAL_PATH=D:/projects/TheRock/math-libs/BLAS/Tensile -DTENSILE_VERSION= -DBUILD_CLIENTS_TESTS=ON -DBUILD_CLIENTS_BENCHMARKS=ON -DLINK_BLIS=OFF && "C:\Program Files\CMake\bin\cmake.exe" -E touch D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/build/compile_commands.json && "C:\Program Files\CMake\bin\cmake.exe" -E touch D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/stamp/configure.stamp && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/build/compile_commands.json D:/projects/TheRock/build/compile_commands_fragment_rocBLAS.json"
[build] [rocBLAS configure] -- Sub-project PKG_CONFIG_PATH: D:/projects/TheRock/build/third-party/sysdeps/windows/zlib/build/stage/lib/rocm_sysdeps/lib/pkgconfig;D:/projects/TheRock/build/third-party/sysdeps/windows/zstd/build/stage/lib/rocm_sysdeps/lib/pkgconfig;
[build] [rocBLAS configure] -- Resolving packages from super-project: ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx
[build] [rocBLAS configure] -- Augmented toolchain PATH=D:/projects/TheRock/build/core/clr/dist/bin;D:/projects/TheRock/build/core/clr/dist/lib/llvm/bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\;C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Python312\Scripts\;C:\Program Files\Python312\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\tools\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Users\Nod-Shark16\AppData\Local\Microsoft\WindowsApps;C:\Users\Nod-Shark16\AppData\Local\Programs\Microsoft VS Code\bin;c:\users\nod-shark16\.local\bin;c:\users\nod-shark16\appdata\roaming\python\python312\scripts;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
[build] [rocBLAS configure] -- Use amdclang to build for amdgpu backend
[build] [rocBLAS configure] -- Resolving system find_package(Threads) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- Resolving system find_package(Python3) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- Resolving super-project find_package(ROCM 0.7.3 QUIET BYPASS_PROVIDER NO_DEFAULT_PATH PATHS D:/projects/TheRock/build/base/rocm-cmake/dist/share/rocm/cmake)
[build] [rocBLAS configure] CMake Deprecation Warning at D:/projects/TheRock/build/base/rocm-cmake/dist/share/rocm/cmake/ROCMConfig.cmake:12 (message):
[build] [rocBLAS configure]   Use of find_package(ROCM) is deprecated as of ROCm 6.4.  Please use
[build] [rocBLAS configure]   find_package(ROCmCMakeBuildTools)
[build] [rocBLAS configure] Call Stack (most recent call first):
[build] [rocBLAS configure]   D:/projects/TheRock/cmake/therock_subproject_dep_provider.cmake:54 (find_package)
[build] [rocBLAS configure]   CMakeLists.txt:57 (find_package)
[build] [rocBLAS configure] 
[build] [rocBLAS configure] 
[build] [rocBLAS configure] -- Resolving super-project find_package(ROCmCMakeBuildTools BYPASS_PROVIDER NO_DEFAULT_PATH PATHS D:/projects/TheRock/build/base/rocm-cmake/dist/share/rocmcmakebuildtools/cmake)
[build] [rocBLAS configure] -- OS detected is unknown
[build] [rocBLAS configure] -- ROCM Platform Version:  is not set, using latest supported gfx list
[build] [rocBLAS configure] -- Using GPU_TARGETS: gfx1100;gfx1101;gfx1102
[build] [rocBLAS configure] -- Resolving super-project find_package(hip REQUIRED BYPASS_PROVIDER NO_DEFAULT_PATH PATHS D:/projects/TheRock/build/core/clr/dist/lib/cmake/hip)
[build] [rocBLAS configure] -- OS: unknown 
[build] [rocBLAS configure] -- Resolving system find_package(Threads) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- Resolving system find_package(Git) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- *** Building rocBLAS commit: e778093683a32d4e3e139f664aa289e55faac7db
[build] [rocBLAS configure] -- ** NOTE: blas2/rocblas_ger_kernels.cpp is compiled with the verbose flag -v for QC purposes.
[build] [rocBLAS configure] -- ** rocblas_library_settings: rocblas
[build] [rocBLAS configure] -- Resolving system find_package(Threads) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- Resolving system find_package(OpenMP) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] -- CLIENT COMMON CXX_OPTIONS: 
[build] [rocBLAS configure] -- CLIENT COMMON LINK: OpenMP::OpenMP_CXX;libomp;Threads::Threads
[build] [rocBLAS configure] -- Resolving system find_package(OPENBLAS) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;hip;HIP;hip-lang;hiprtc;hipblas-common;ROCmCMakeBuildTools;ROCM;GTest;msgpack-cxx)
[build] [rocBLAS configure] CMake Error at D:/projects/TheRock/cmake/therock_subproject_dep_provider.cmake:62 (find_package):
[build] [rocBLAS configure]   Could not find a package configuration file provided by "OPENBLAS" with any
[build] [rocBLAS configure]   of the following names:
[build] [rocBLAS configure] 
[build] [rocBLAS configure]     OPENBLASConfig.cmake
[build] [rocBLAS configure]     openblas-config.cmake
[build] [rocBLAS configure] 
[build] [rocBLAS configure]   Add the installation prefix of "OPENBLAS" to CMAKE_PREFIX_PATH or set
[build] [rocBLAS configure]   "OPENBLAS_DIR" to a directory containing one of the above files.  If
[build] [rocBLAS configure]   "OPENBLAS" provides a separate development package or SDK, be sure it has
[build] [rocBLAS configure]   been installed.
[build] [rocBLAS configure] Call Stack (most recent call first):
[build] [rocBLAS configure]   clients/CMakeLists.txt:176 (find_package)
[build] [rocBLAS configure] 
[build] [rocBLAS configure] 
[build] [rocBLAS configure] CMake Error at clients/CMakeLists.txt:176 (find_package):
[build] [rocBLAS configure]   Could not find a package configuration file provided by "OPENBLAS" with any
[build] [rocBLAS configure]   of the following names:
[build] [rocBLAS configure] 
[build] [rocBLAS configure]     OPENBLASConfig.cmake
[build] [rocBLAS configure]     openblas-config.cmake
[build] [rocBLAS configure] 
[build] [rocBLAS configure]   Add the installation prefix of "OPENBLAS" to CMAKE_PREFIX_PATH or set
[build] [rocBLAS configure]   "OPENBLAS_DIR" to a directory containing one of the above files.  If
[build] [rocBLAS configure]   "OPENBLAS" provides a separate development package or SDK, be sure it has
[build] [rocBLAS configure]   been installed.
[build] [rocBLAS configure] 
[build] [rocBLAS configure] 
[build] [rocBLAS configure] -- Configuring incomplete, errors occurred!
[build] [rocBLAS configure completed in 1 seconds]
```

Relevant sub-project code, with some `find_library` / `find_package` and hardcoded paths:
https://github.com/ROCm/rocBLAS/blob/d93e919f945e76ee89457c83d72aac4cb473f492/clients/CMakeLists.txt#L117-L181

I see https://github.com/ROCm/TheRock/blob/main/cmake/finders/FindBLAS.cmake already, with `OpenBLAS` package name. Maybe case sensitivity difference?

### PR DESCRIPTION
**Pull request by ScottTodd**
resolves https://github.com/ROCm/TheRock/issues/482

Summary of proposed changes:
- Fix casing of `OpenBLAS` package.
- Fix ordering of `#include <windows.h>`.

### CODE REVIEW

**Review by TorreZuk — COMMENTED** [review]
Looks fine, just need to wait on windows build and test pipeline to pass.

**Review by TorreZuk — APPROVED** [review]
Our windows build and tests passed but of course with AOCL.    Can you mention the version of OpenBLAS you are using.   As we use AOCL in our CI so can you work on full quality control testing with OpenBLAS on windows.  Did you run all tests?   I made a tech debt ticket but if you have CI nodes testing with OpenBLAS it may be better if you can work on it.

**Comment by TorreZuk** [comment]
PS - as our windows build didn't need the include changes curious how yours diverges in build flags or compiler.   Could be a LEAN variation... but can be figure out.

**Comment by ScottTodd** [comment]
> Can you mention the version of OpenBLAS you are using.

We are using OpenBLAS v0.3.29 in [TheRock](https://github.com/ROCm/TheRock) at the moment. That is latest release on GitHub, from 2025-01-12: https://github.com/OpenMathLib/OpenBLAS/releases. That version is pinned here: https://github.com/ROCm/TheRock/blob/9b7ef5e13ac1f4f7d2fea75639785e08a464bc43/third-party/host-blas/CMakeLists.txt#L10-L19 and made available to `find_package(OpenBLAS CONFIG REQUIRED)` here: https://github.com/ROCm/TheRock/blob/9b7ef5e13ac1f4f7d2fea75639785e08a464bc43/cmake/finders/FindBLAS.cmake#L6-L17.

> Did you run all tests?

I ran some tests on my dev machine (AMD Radeon Pro W7900, gfx1200): https://github.com/ROCm/TheRock/issues/482#issuecomment-2840183883. Initial results were promising, with only a few failures that I have not triaged yet like this: 

```
[----------] 21 tests from _/check_numerics_vector
C:\Users\NOD-SH~1\AppData\Local\Temp\comgr-84055f\input\Assembly Text:60:2: error: undefined label '.not_s_trap'
 s_cbranch_scc0 .not_s_trap
 ^
```

I stopped the test process after ~10 minutes to switch tasks. We're still bootstrapping projects and have not yet onboarded and validated all tests or enabled them in continuous integration workflows on dedicated test machines. That will come once enough of the projects (and all their transitive deps) configure/build as expected.

> PS - as our windows build didn't need the include changes curious how yours diverges in build flags or compiler. Could be a LEAN variation... but can be figure out.

Yeah that's strange to me too. I got the hint to switch the include order for `<windows.h>` from a similar set of compatibility fixes for hipBLASLt: https://github.com/ROCm/hipBLASLt/commit/57d3aaf02554f8407d5eba6ef255836725f65aac. Other projects I've worked on have also required it to be included before other headers, in which case we usually centralize such platform-specific includes and set some coding style practices around that.

File: clients/gtest/rocblas_test.cpp [hunk 1]
```diff
@@ -21,19 +21,24 @@
...
-#include "client_utility.hpp"
 
-#include <cstdlib>
-#include <exception>
-#include <regex>
 #ifdef WIN32
+// Must include windows.h before dependent headers.
+// Specifically this must be before client_utility.hpp uses `#pragma GCC poison`
+// to poison 'ctime' and 'abort', as those are used in standard library headers.
 #include <windows.h>
```
Comment (apwojcik) [inline clients/gtest/rocblas_test.cpp:29]: If no Cryptography, DDE, RPC, Shell, and Windows sockets are required, you should prepend `#include <Windows.h>` with `#define WIN32_LEAN_AND_MEAN` as such:
```C++
#idefine WIN32_LEAN_AND_MEAN
#include <Windows.h>
```
The correct case of the `Windows.h` is with the capital letter (for MSFT)
There are more flags to minimize the footprint. Read it more here: https://learn.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers
But usually `WIN32_LEAN_AND_MEAN` is enough.

Comment (TorreZuk) [reply clients/gtest/rocblas_test.cpp:29]: The LEAN define is added in our toolchain-windows.cmake where used with the original fail fast design pattern.  This is a new windows build pipeline which may not use that, I will need to confirm that sometime, but for now if both builds succeed this is fine to merge.

Comment (ScottTodd) [reply clients/gtest/rocblas_test.cpp:29]: TheRock currently sets the same defines for each ROCm sub-project with a common toolchain file constructed here: https://github.com/ROCm/TheRock/blob/b5412338880fed74976b2f4408e0e06cbccc683f/cmake/therock_subproject.cmake#L1111-L1119 . I did not need to add the `WIN32_LEAN_AND_MEAN` define for build correctness, but agree that it could be beneficial to add. Definitely worth doing a scrub through and setting more build size and performance flags, but might need to customize defines/flags per sub-project as in the current project-specific toolchain files.

Comment (TorreZuk) [reply clients/gtest/rocblas_test.cpp:29]: Well that explains the error you see vs. what we get in our windows CI.   It is not for correctness but for fewer dependencies being included.  Some component other than rocBLAS may use the dependencies @apwojcik listed but probably not if they copied the rocBLAS toolchain (which was done first).

**Comment by TorreZuk** [comment]
@ScottTodd are you going to merge this or close this PR and adopt WIN32_LEAN_AND_MEAN ?

**Comment by ScottTodd** [comment]
> @ScottTodd are you going to merge this or close this PR and adopt WIN32_LEAN_AND_MEAN ?

I don't have permissions to merge.

The OPENBLAS change will be required regardless, but I can test if the `clients/gtest/rocblas_test.cpp` changes are still needed with `WIN32_LEAN_AND_MEAN`.

**Comment by TorreZuk** [comment]
@ScottTodd I can merge now if you want, as okay to merge support for no define set

**Comment by ScottTodd** [comment]
Just got a successful build of rocBLAS with the `clients/gtest/rocblas_test.cpp` patch dropped and `-DWIN32_LEAN_AND_MEAN` added to `CMAKE_CXX_FLAGS`. If you're okay with the patch then it would be helpful for others in the future who may have the define unset, yes. I'll see if I can roll that define out across all subprojects in TheRock for its general benefits.

**Comment by ScottTodd** [comment]
So yes, please merge when you like :)

**Comment by ScottTodd** [comment]
> I'll see if I can roll that define out across all subprojects in TheRock for its general benefits.

FYI that went well: https://github.com/ROCm/TheRock/pull/607. Looks like all subprojects are compatible with `WIN32_LEAN_AND_MEAN`, though I only tested the _build_ so if there are somehow runtime errors I'll have missed that.
